### ISSUE TITLE
Issue with srsRAN Project

### ISSUE THREAD

**Issue by roskeys** [PrincetonUniversity/NR-Scope#28]
Dear developers.

Thank you for open source this great application. Currently I have setup the environment containing srsRAN + open5GS running with n78 20MHz. 
But I met some issue in using NR-Scope even to detect the phone connecting to the srsRAN project base station. From the log, I can see messages like `SIB 1 Decoded.`. 
Afterwards, I see the logs below, and then no mather how I toggle the airplane mode of the phone, NR-Scope does not show any other logs over there indicating it detects a new UE.
```
Workers are initializing, skip sf_rount: 0, sfn: 446, slot: 9
srsran_dft_replan
RACH decoder initialized..
```

Here's my srsRAN configuration.
```
amf:
  addr: 127.0.0.5                                                 # The address or hostname of the AMF.
  bind_addr: 127.0.0.1                                            # A local IP that the gNB binds to for traffic from the AMF.

ru_sdr:
  device_driver: uhd                                              # The RF driver name.
  device_args: type=b200                           # Optionally pass arguments to the selected RF driver.
  srate: 23.04                                                    # RF sample rate might need to be adjusted according to selected bandwidth.
  otw_format: sc12
  tx_gain: 80                                                     # Transmit gain of the RF might need to adjusted to the given situation.
  rx_gain: 40                                                     # Receive gain of the RF might need to adjusted to the given situation.

cell_cfg:
  dl_arfcn: 628500                                                # ARFCN of the downlink carrier (center frequency).
  band: 78                                                        # The NR band.
  channel_bandwidth_MHz: 20                                       # Bandwith in MHz. Number of PRBs will be automatically derived.
  common_scs: 30                                                  # Subcarrier spacing in kHz used for data.
  plmn: "00101"                                                   # PLMN broadcasted by the gNB.
  tac: 1                                                          # Tracking area code (needs to match the core configuration).
  pci: 1                                                          # Physical cell ID.
```

And for NR-Scope config.yaml
```
nof_usrp_dev: 1
usrp_setting_0:
  ssb_freq: 3421920000 # Set to the ssb frequency of the cell, could be obtained with the cell scan function
  rf_args: "type=b200" # For B210
  # rf_args: "clock=external,type=x300,serial=32B0F2F,master_clock_rate=200000000,sampling_rate=25000000" ## For TwinRX daughterboard
  # rf_args: "clock=external,type=x300,sampling_rate=23040000" ## For CBX daughterboard
  rx_gain: 30 # for x310 CBX, max rx gain is 31.5, for b210, it's around 80, for x310 TwinRX, max rx gain is 90
  min_rx_gain: 0
  max_rx_gain: 40
  srate_hz: 23040000 # the sampling rate of USRP, integer division of 200MHz for TwinRX, and 5G sampling rate for CBX: 11520000 or 23040000
  srsran_srate_hz: 23040000 # the sampling for real signal processing, should be in 5G sampling rate, multiple of 1.92 MHz. 
  nof_carriers: 1 # srsRAN rf setting, always set to be 1 for now. 
  nof_antennas: 1 # srsRAN rf setting, always set to be 1 for now.
  scs_index: 1 #(0: 15kHz, 1: 30kHz, ..., the u in standard)
  rf_log_level: "debug"
  nof_rnti_worker_groups: 16 # number of of threads for DCI decoding, each will divide the UEs into small groups
  nof_bwps: 1 # number of BWP of the cell
  nof_workers: 16 # using worker pool to asynchronously process the slot data
  cpu_affinity: false # pin the worker's thread into CPU or not.
```

**Comment by WanHaoRan** [comment]
Hello, thanks for trying our tool. In the NR-Scope config file, could you change the rx_gain to 75 and max_rx_gain to 76.5, which is near the B210 maximum rx gain. Also, did you use the GSPDO on both sides? If not, the NR-Scope might lose synchronization with the srsRAN during the session.

For the srsRAN cell, could you remove the "pdsch_hl_cfg.mcs_table = srsran_mcs_table_256qam;" and "pusch_hl_cfg.mcs_table = srsran_mcs_table_256qam;" in the dci_decoder.cc and make again? This is empirically set according to commercial cells, as this information is sometimes sent through encrypted RRCReconfiguration.

**Comment by WanHaoRan** [comment]
Hey roskeys, thanks for your update and trying the code with the GPSDO. I've been trying to use the srsRAN today, and I faced the same issue -- the NR-Scope can decode the SIB 1 but the UE connections seem to be hard to decode. This code is initially developed and tested on srsRAN, we also demoed code at Mobicom with srsRAN. And the code runs smoothly with the commercial cells nearby me using main and fixed_rnti branch. Check the stdout [stdout.txt](https://github.com/user-attachments/files/20024771/stdout.txt) and the csv file [a.csv](https://github.com/user-attachments/files/20024776/a.csv). 

A total three phones should be OK, you don't need a large number of workers and threads. nof_rnti_worker_groups can be 1 or  2 and nof_workers can be 4. 

I will keep trying with the srsRAN until I figure it out. Right now I am running both NR-Scope and the srsRAN on the same desktop machine, which could be a problem. I will try to run them at two separate machines and see if anything could be improved. I will update if I find anything new, thanks!

**Comment by WanHaoRan** [comment]
Hey, sorry I provided the wrong information. I used the wrong SIM card and the phone was connecting to another base station... 
Running both srsRAN and NR-Scope on the same PC is fine. Here are my config files for the NR-Scope and the srsCU and srsDU. I think it's easy to migrate to srsgNB with these config files. 

config.yaml for nrscope:
```nof_usrp_dev: 1
usrp_setting_0:
  ssb_freq: 3744480000 # Set to the ssb frequency of the cell, could be obtained with the cell scan function
  rf_args: "type=x300,serial=30A4446,clock=external" # For B210
  # rf_args: "clock=external,type=x300,serial=32B0F2F,master_clock_rate=200000000,sampling_rate=25000000" ## For TwinRX daughterboard
  # rf_args: "clock=external,type=x300,sampling_rate=23040000" ## For CBX daughterboard
  rx_gain: 30 # for x310 CBX, max rx gain is 31.5, for b210, it's around 80, for x310 TwinRX, max rx gain is 90
  min_rx_gain: 0
  max_rx_gain: 31.5
  srate_hz: 23040000 # the sampling rate of USRP, integer division of 200MHz for TwinRX, and 5G sampling rate for CBX: 11520000 or 23040000
  srsran_srate_hz: 23040000 # the sampling for real signal processing, should be in 5G sampling rate, multiple of 1.92 MHz. 
  nof_carriers: 1 # srsRAN rf setting, always set to be 1 for now. 
  nof_antennas: 1 # srsRAN rf setting, always set to be 1 for now.
  scs_index: 1 #(0: 15kHz, 1: 30kHz, ..., the u in standard)
  rf_log_level: "debug"
  nof_rnti_worker_groups: 4 # number of of threads for DCI decoding, each will divide the UEs into small groups
  nof_bwps: 1 # number of BWP of the cell
  nof_workers: 4 # using worker pool to asynchronously process the slot data
  cpu_affinity: false # pin the worker's thread into CPU or not.
  use_gpsdo: false # gpsdo not required but recommended, as the software synchronization on a higher bandwidth cell has overflows and missed DCIs

  log_name: "a.csv"
  google_dataset_id: "ngscope5g_dci_log_wanhr"

```


config for srsDU:
```# Example config for a DU with one 20MHz TDD cell using a USRP as RF frontend.
f1ap:
  cu_cp_addr: 127.0.10.1
  bind_addr: 127.0.10.3
nru:
  bind_addr: 127.0.10.3

ru_sdr:
  device_driver: uhd
  device_args: type=b200,clock=external
  srate: 23.04
  tx_gain: 70
  rx_gain: 70
  clock: external

cell_cfg:
  dl_arfcn: 650000
  band: 78
  channel_bandwidth_MHz: 20
  common_scs: 30
  plmn: "00101"
  tac: 7
  pci: 1

log:
  filename: /tmp/du.log
  all_level: debug

pcap:
  mac_enable: true
  mac_filename: /tmp/du_mac.pcap
  f1ap_enable: true
  f1ap_filename: /tmp/du_f1ap.pcap
  f1u_enable: true
  f1u_filename: /tmp/du_f1u.pcap
  rlc_filename: /tmp/gnb_rlc.pcap       # Optional TEXT (tmp/gnb_rlc.pcap). Path for RLC PCAPs.
  rlc_rb_type: all                      # Optional TEXT. Sets the RLC PCAP RB type. Supported: [all, srb, drb].
  rlc_enable: true                     # Optional BOOLEAN (false). Enable/disable RLC packet capture. Supported: [false, true]. 
```

Config for srsCU:
```
# Example config for a locally deployed CU listening on the localhost interface for a DU connection

cu_cp:
  amf:
    addr: 127.0.0.20
    port: 38412
    bind_addr: 127.0.10.2
    supported_tracking_areas:
      - tac: 7
        plmn_list:
          - plmn: "00101"
            tai_slice_support_list:
              - sst: 1
  f1ap:
    bind_addr: 127.0.10.1

cu_up:
  nru:
    bind_addr: 127.0.10.1

log:
  filename: /tmp/cu.log
  all_level: debug

pcap:
  ngap_filename: /tmp/cu_ngap.pcap
  ngap_enable: true
  f1u_filename: /tmp/gnb_f1u.pcap      # Optional TEXT (/tmp/gnb_f1u.pcap). Path for F1-U (NRU) PCAPs. 
  f1u_enable: true                     # Optional BOOLEAN (false). Enable/disable F1-U (NRU) packet capture. Supported: [false, true].
  n3_filename: /tmp/gnb_n3.pcap         # Optional TEXT (/tmp/gnb_n3.pcap). Path for N3 PCAPs. 
  n3_enable: true                      # Optional BOOLEAN (false). Enable/disable N3 packet capture. Supported: [false, true].
```

For the DU, I tried it with both B210 and X310, both can work very well. Please check the branch "srsran" of NR-Scope to work with srsRAN, basically, it just comment the lines I commented before. Thanks!
